restored production config

diff --git a/.github/workflows/cicd-pipeline.yml b/.github/workflows/cicd-pipeline.yml
--- a/.github/workflows/cicd-pipeline.yml
+++ b/.github/workflows/cicd-pipeline.yml
@@ -103,8 +103,7 @@ jobs:
   # associated with a commit on ANY branch would trigger a production deployment!
   Tree-Check:
     # if tagged commit (for Deploy-Prod) or on main branch (for Deploy-Dev)
-    # if: (startsWith(github.ref, 'refs/tags/selt2022_sprint')) || (github.ref == 'refs/heads/main')
-    if: (startsWith(github.ref, 'refs/tags/test_tag')) || (github.ref == 'refs/heads/pipeline-beta-deploy')
+    if: (startsWith(github.ref, 'refs/tags/selt2022_sprint')) || (github.ref == 'refs/heads/main')
     runs-on: ubuntu-latest
     outputs:
       commit_hash: ${{ env.COMMIT_HASH }}
@@ -118,12 +117,12 @@ jobs:
         run: |
           git fetch --depth 1
           COMMIT_HASH=${{ github.sha }}
-          MAIN_HEAD=$(git log -n 1 --pretty=format:"%H" origin/pipeline-beta-deploy)
+          MAIN_HEAD=$(git log -n 1 --pretty=format:"%H" origin/main)
           echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
           echo "MAIN_HEAD=$MAIN_HEAD" >> $GITHUB_ENV
           echo "commit hash: $COMMIT_HASH"
           echo "main head: $MAIN_HEAD"
-          if [ "$MAIN_HEAD" != "$COMMIT_HASH" ]; then echo "Commit hash is not head of main. A deployment will not be made."; fi
+          if [ "$MAIN_HEAD" != "$COMMIT_HASH" ]; then echo "Commit hash is not head of main. A deployment cannot be made." && exit 1; fi
 
   # deploys current main branch to 'uiowa-grad-app-beta' for quality assurance
   # note: database is not shared with prod, so we use seeds here
@@ -139,8 +138,7 @@ jobs:
       RAILS_ENV: production
       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
       HEROKU_DEBUG_RAILS_RUNNER: 1
-      # HEROKU_APP_NAME: uiowa-grad-app-beta
-      HEROKU_APP_NAME: polar-hamlet-10669
+      HEROKU_APP_NAME: uiowa-grad-app-beta
     steps:
       - name: Checkout main branch
         uses: actions/checkout@v3
@@ -179,8 +177,7 @@ jobs:
   # on the current sprint iteration
   Deploy-Prod:
     # ONLY deploy on TAGGED PUSH to MAIN branch of UIOWAjohnsonhj/selt2022_teamprojects-team-4
-    # if: (github.event_name == 'push') && (needs.Tree-Check.outputs.commit_hash == needs.Tree-Check.outputs.main_head) && (startsWith(github.ref, 'refs/tags/selt2022_sprint')) && (github.repository == 'UIOWAjohnsonhj/selt2022_teamprojects-team-4')
-    if: (github.event_name == 'push') && (needs.Tree-Check.outputs.commit_hash == needs.Tree-Check.outputs.main_head) && (startsWith(github.ref, 'refs/tags/test_tag')) && (github.repository == 'UIOWAjohnsonhj/selt2022_teamprojects-team-4')
+    if: (github.event_name == 'push') && (needs.Tree-Check.outputs.commit_hash == needs.Tree-Check.outputs.main_head) && (startsWith(github.ref, 'refs/tags/selt2022_sprint')) && (github.repository == 'UIOWAjohnsonhj/selt2022_teamprojects-team-4')
     needs:
       - Deploy-Dev
       - Tree-Check
@@ -208,8 +205,7 @@ jobs:
         env:
           SPRINT1_START: ${{ fromJson(env.HEROKU_MAPPINGS).sprint1_start }}
           SPRINT1_END: ${{ fromJson(env.HEROKU_MAPPINGS).sprint1_end }}
-          # HEROKU_APP_NAME: ${{ fromJson(env.HEROKU_MAPPINGS).sprint1_app_name }}
-          HEROKU_APP_NAME: polar-hamlet-10669
+          HEROKU_APP_NAME: ${{ fromJson(env.HEROKU_MAPPINGS).sprint1_app_name }}
         
       # app name: uiowa-grad-app-v2
       # 2022-11-10 <= current_date <= 2022-11-27
@@ -218,8 +214,7 @@ jobs:
         env:
           SPRINT2_START: ${{ fromJson(env.HEROKU_MAPPINGS).sprint2_start }}
           SPRINT2_END: ${{ fromJson(env.HEROKU_MAPPINGS).sprint2_end }}
-          # HEROKU_APP_NAME: ${{ fromJson(env.HEROKU_MAPPINGS).sprint2_app_name }}
-          HEROKU_APP_NAME: polar-hamlet-10669
+          HEROKU_APP_NAME: ${{ fromJson(env.HEROKU_MAPPINGS).sprint2_app_name }}
 
       # app name: uiowa-grad-app-v3
       # 2022-11-28 <= current_date <= 2022-12-09
@@ -228,8 +223,7 @@ jobs:
         env:
           SPRINT3_START: ${{ fromJson(env.HEROKU_MAPPINGS).sprint3_start }}
           SPRINT3_END: ${{ fromJson(env.HEROKU_MAPPINGS).sprint3_end }}
-          # HEROKU_APP_NAME: ${{ fromJson(env.HEROKU_MAPPINGS).sprint3_app_name }}
-          HEROKU_APP_NAME: polar-hamlet-10669
+          HEROKU_APP_NAME: ${{ fromJson(env.HEROKU_MAPPINGS).sprint3_app_name }}
 
       - name: Create Heroku app (if needed)
         continue-on-error: true
